# Ansible Inventory - Auto-generated by Terraform
# Generated on: ${timestamp()}

[rocky_vms]
%{ for vm in vms ~}
${vm.name} ansible_host=${vm.default_ipv4_address} ansible_user=${ssh_user} ansible_ssh_common_args='-o StrictHostKeyChecking=no'
%{ endfor ~}

[rocky_vms:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

# VM Details
%{ for vm in vms ~}
# ${vm.name}: ${vm.default_ipv4_address} (VM ID: ${vm.vmid})
%{ endfor ~}
