name: Packer Build and Deploy

on:
  workflow_dispatch:
    inputs:
      proxmox_node:
        description: 'Proxmox node name'
        required: true
        type: string
        default: 'tcnhq-prxmx01'
      vm_id:
        description: 'VM ID (0 for auto-assign)'
        required: true
        type: string
        default: '110'
      vm_name:
        description: 'VM name'
        required: true
        type: string
        default: 'rocky-linux-test'
      template_name:
        description: 'Source template name'
        required: true
        type: string
        default: 'rocky-linux-stig-manual'

env:
  PACKER_LOG: 1
  PACKER_LOG_PATH: packer.log

jobs:
  validate:
    name: Validate Packer Configuration
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Packer
      uses: hashicorp/setup-packer@main

    - name: Initialize Packer plugins
      run: |
        cd milestone1-packer
        packer init packer.pkr.hcl

    - name: Validate Packer configuration
      run: |
        cd milestone1-packer
        packer validate packer.pkr.hcl

  build:
    name: Build VM from Template
    runs-on: ubuntu-latest
    needs: validate
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Packer
      uses: hashicorp/setup-packer@main

    - name: Initialize Packer plugins
      run: |
        cd milestone1-packer
        packer init packer.pkr.hcl

    - name: Build VM from Template
      env:
        PACKER_VAR_proxmox_url: ${{ secrets.PROXMOX_URL }}
        PACKER_VAR_proxmox_username: ${{ secrets.PROXMOX_USERNAME }}
        PACKER_VAR_proxmox_password: ${{ secrets.PROXMOX_PASSWORD }}
        PACKER_VAR_proxmox_node: ${{ github.event.inputs.proxmox_node }}
        PACKER_VAR_template_name: ${{ github.event.inputs.template_name }}
        PACKER_VAR_ssh_password: ${{ secrets.SSH_PASSWORD }}
        PACKER_VAR_vm_id: ${{ github.event.inputs.vm_id }}
        PACKER_VAR_vm_name: ${{ github.event.inputs.vm_name }}
        PACKER_VAR_build_id: ${{ github.run_id }}
      run: |
        cd milestone1-packer
        packer build packer.pkr.hcl

    - name: Upload build logs
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: packer-logs
        path: milestone1-packer/packer.log

  notify:
    name: Notify Build Status
    runs-on: ubuntu-latest
    needs: [build]
    if: always()
    steps:
    - name: Notify Success
      if: needs.build.result == 'success'
      run: |
        echo "✅ Packer build completed successfully!"
        echo "Build ID: ${{ github.run_id }}"
        echo "Proxmox Node: ${{ github.event.inputs.proxmox_node }}"
        echo "Template Name: ${{ github.event.inputs.template_name }}"
        echo "VM ID: ${{ github.event.inputs.vm_id }}"
        echo "VM Name: ${{ github.event.inputs.vm_name }}"

    - name: Notify Failure
      if: needs.build.result == 'failure'
      run: |
        echo "❌ Packer build failed!"
        echo "Check the logs for details."
        exit 1