name: Packer Build and Deploy

on:
  push:
    branches: [ main ]
    paths: [ 'milestone1-packer/**' ]
  pull_request:
    branches: [ main ]
    paths: [ 'milestone1-packer/**' ]
  workflow_dispatch:
    inputs:
      vm_name:
        description: 'VM name (optional)'
        required: false
        type: string
      vm_id:
        description: 'VM ID (0 for auto-assign)'
        required: false
        type: string
        default: '0'

env:
  PACKER_LOG: 1
  PACKER_LOG_PATH: packer.log

jobs:
  validate:
    name: Validate Packer Configuration
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Packer
      uses: hashicorp/setup-packer@main

    - name: Validate Packer configuration
      run: |
        cd milestone1-packer
        packer validate packer.pkr.hcl

  build:
    name: Build VM from Template
    runs-on: ubuntu-latest
    needs: validate
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Packer
      uses: hashicorp/setup-packer@main

    - name: Build VM from Template
      env:
        PACKER_VAR_proxmox_url: ${{ secrets.PROXMOX_URL }}
        PACKER_VAR_proxmox_username: ${{ secrets.PROXMOX_USERNAME }}
        PACKER_VAR_proxmox_password: ${{ secrets.PROXMOX_PASSWORD }}
        PACKER_VAR_proxmox_node: ${{ secrets.PROXMOX_NODE }}
        PACKER_VAR_ssh_password: ${{ secrets.SSH_PASSWORD }}
        PACKER_VAR_vm_id: ${{ github.event.inputs.vm_id || github.run_number }}
        PACKER_VAR_vm_name: ${{ github.event.inputs.vm_name || format('rocky-linux-{0}', github.run_number) }}
        PACKER_VAR_build_id: ${{ github.run_id }}
      run: |
        cd milestone1-packer
        packer build packer.pkr.hcl

    - name: Upload build logs
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: packer-logs
        path: milestone1-packer/packer.log

  notify:
    name: Notify Build Status
    runs-on: ubuntu-latest
    needs: [build]
    if: always()
    steps:
    - name: Notify Success
      if: needs.build.result == 'success'
      run: |
        echo "✅ Packer build completed successfully!"
        echo "Build ID: ${{ github.run_id }}"
        echo "VM ID: ${{ github.event.inputs.vm_id || github.run_number }}"
        echo "VM Name: ${{ github.event.inputs.vm_name || format('rocky-linux-{0}', github.run_number) }}"

    - name: Notify Failure
      if: needs.build.result == 'failure'
      run: |
        echo "❌ Packer build failed!"
        echo "Check the logs for details."
        exit 1